version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - IMAGE_URI="780489678393.dkr.ecr.us-east-1.amazonaws.com/repo-publish:latest"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t repo-publish .
      - docker tag repo-publish:latest 780489678393.dkr.ecr.us-east-1.amazonaws.com/repo-publish:latest   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 780489678393.dkr.ecr.us-east-1.amazonaws.com/repo-publish:latest
      - printf '[{"name":"repo-publish","imageUri":"780489678393.dkr.ecr.us-east-1.amazonaws.com/repo-publish:latest"}]' > images.json
      - cat images.json
artifacts:
  files: images.json
